config/routes.rb
Phone::Application.routes.draw do

  resources :simlogs

  resources :hollydays

  get "descriptioncalls/show"

  get "descriptioncalls/update"
  resources :userlogs
  resources :operators
  resources :schedules
  resources :cfus
  resources :sumlimits
  resources :users
  resources :simnumlogs
  resources :sims
  get "page/main"

  get "page/help"

  get "page/about"

  resources :tnumbers

  resources :tarifs
  resources :descriptioncalls
  resources :report
  match '/calllogs/' => 'calllogs#index', :via => :get
  match '/upload/' => 'upload#index', :via => :get
  match '/upload/' => 'upload#upload', :via => :post
  match '/simnumlogs/:id/endperiod' => 'simnumlogs#endperiod', :as => :endperiod_simnumlog
  match '/userlogs/:id/endperiod' => 'userlogs#endperiod', :as => :endperiod_userlog

  root :to => 'page#main'

end

app/models/simlog.rb
class Simlog < ActiveRecord::Base
  attr_accessible :pda, :period_id, :sim_id, :user_id
  belongs_to :user
  belongs_to :sim
  belongs_to :user
  belongs_to :period
end

app/controllers/simlogs_controller.rb
class SimlogsController < ApplicationController
  # GET /simlogs
  # GET /simlogs.json
  def index
    @simlogs = Simlog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @simlogs }
    end
  end

  # GET /simlogs/1
  # GET /simlogs/1.json
  def show
    @simlog = Simlog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @simlog }
    end
  end

  # GET /simlogs/new
  # GET /simlogs/new.json
  def new
    @period = Period.new
    @period.simlog.build
    @period.datein = Time.zone.now

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @simlog }
    end
  end

  # GET /simlogs/1/edit
  def edit
    @simlog = Simlog.find(params[:id])
  end

  # POST /simlogs
  # POST /simlogs.json
  def create
    #logger.debug params
    @period = Period.new(params[:period])
    
    respond_to do |format|
      if @period.save
        format.html { redirect_to Simlog, notice: 'Simlog was successfully created.' }
        format.json { render json: @simlog, status: :created, location: @simlog }
      else
        format.html { render action: "new" }
        format.json { render json: @simlog.errors, status: :unprocessable_entity }
      end
    end
  end





  # PUT /simlogs/1
  # PUT /simlogs/1.json
  def update
    @simlog = Simlog.find(params[:id])

    respond_to do |format|
      if @simlog.update_attributes(params[:simlog])
        format.html { redirect_to @simlog, notice: 'Simlog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @simlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simlogs/1
  # DELETE /simlogs/1.json
  def destroy
    @simlog = Simlog.find(params[:id])
    @simlog.destroy

    respond_to do |format|
      format.html { redirect_to simlogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/simlogs_helper.rb
module SimlogsHelper
end

app/views/simlogs/_form.html.erb
<%= form_for(@simlog) do |f| %>
  <% if @simlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@simlog.errors.count, "error") %> prohibited this simlog from being saved:</h2>

      <ul>
      <% @simlog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sim_id %><br />
    <%= f.number_field :sim_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :period_id %><br />
    <%= f.number_field :period_id %>
  </div>
  <div class="field">
    <%= f.label :pda %><br />
    <%= f.check_box :pda %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/simlogs/_new_form.html.erb
<%= form_for @period, :url => '/simlogs/', userlogs_path => false do |cf| %>

  <%= cf.fields_for :simlog do |f| %>
  <div class="field">
    <%= f.label :sim_id %><br />
    <%= f.collection_select(:sim_id, Sim.where(:id =>Sim.notusesim_id), :id, :sirealnumber ) %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select(:user_id, User.all, :id, :secondname ) %>
  </div>
  <div class="field">
    <%= f.label :pda %><br />
    <%= f.check_box :pda %>
  </div>
  <% end %>
  

  <div class="field">
    <%= cf.label :datein_text %><br />
    <%= cf.text_field :datein_text %>
  </div>
  <div class="actions">
    <%= cf.submit %>
  </div>
<% end %>

app/views/simlogs/edit.html.erb
<h1>Editing simlog</h1>

<%= render 'form' %>

<%= link_to 'Show', @simlog %> |
<%= link_to 'Back', simlogs_path %>

app/views/simlogs/index.html.erb
<h1>Listing simlogs</h1>

<table>
  <tr>
    <th>Sim</th>
    <th>User</th>
    <th>Period</th>
    <th>Pda</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @simlogs.each do |simlog| %>
  <tr>
    <td><%= simlog.sim_id %></td>
    <td><%= simlog.user_id %></td>
    <td><%= simlog.period_id %></td>
    <td><%= simlog.pda %></td>
    <td><%= link_to 'Show', simlog %></td>
    <td><%= link_to 'Edit', edit_simlog_path(simlog) %></td>
    <td><%= link_to 'Destroy', simlog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Simlog', new_simlog_path %>

app/views/simlogs/new.html.erb
<h1>New simlog</h1>

<%= render 'new_form' %>

<%= link_to 'Back', simlogs_path %>

app/views/simlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sim:</b>
  <%= @simlog.sim_id %>
</p>

<p>
  <b>User:</b>
  <%= @simlog.user_id %>
</p>

<p>
  <b>Period:</b>
  <%= @simlog.period_id %>
</p>

<p>
  <b>Pda:</b>
  <%= @simlog.pda %>
</p>


<%= link_to 'Edit', edit_simlog_path(@simlog) %> |
<%= link_to 'Back', simlogs_path %>