config/routes.rb
Phone::Application.routes.draw do

  resources :simlogs

  resources :hollydays

  get "descriptioncalls/show"

  get "descriptioncalls/update"
  resources :userlogs
  resources :operators
  resources :schedules
  resources :cfus
  resources :sumlimits
  resources :users
  resources :simnumlogs
  resources :sims
  get "page/main"

  get "page/help"

  get "page/about"

  resources :tnumbers

  resources :tarifs
  resources :descriptioncalls
  resources :report
  match '/calllogs/' => 'calllogs#index', :via => :get
  match '/upload/' => 'upload#index', :via => :get
  match '/upload/' => 'upload#upload', :via => :post
  match '/simnumlogs/:id/endperiod' => 'simnumlogs#endperiod', :as => :endperiod_simnumlog
  match '/userlogs/:id/endperiod' => 'userlogs#endperiod', :as => :endperiod_userlog

  root :to => 'page#main'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :timein, :timeout
  has_many :userlog
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, :notice => 'Schedule was successfully created.' }
        format.json { render :json => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new" }
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, :notice => 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :timein %><br />
    <%= f.time_select :timein %>
  </div>
  <div class="field">
    <%= f.label :timeout %><br />
    <%= f.time_select :timeout %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <tr>
    <th>Timein</th>
    <th>Timeout</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.timein %></td>
    <td><%= schedule.timeout %></td>
    <td><%= link_to 'Show', schedule %></td>
    <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
    <td><%= link_to 'Destroy', schedule, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Timein:</b>
  <%= @schedule.timein %>
</p>

<p>
  <b>Timeout:</b>
  <%= @schedule.timeout %>
</p>


<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>