config/routes.rb
Phone::Application.routes.draw do

  resources :simlogs

  resources :hollydays

  get "descriptioncalls/show"

  get "descriptioncalls/update"
  resources :userlogs
  resources :operators
  resources :schedules
  resources :cfus
  resources :sumlimits
  resources :users
  resources :simnumlogs
  resources :sims
  get "page/main"

  get "page/help"

  get "page/about"

  resources :tnumbers

  resources :tarifs
  resources :descriptioncalls
  resources :report
  match '/calllogs/' => 'calllogs#index', :via => :get
  match '/upload/' => 'upload#index', :via => :get
  match '/upload/' => 'upload#upload', :via => :post
  match '/simnumlogs/:id/endperiod' => 'simnumlogs#endperiod', :as => :endperiod_simnumlog
  match '/userlogs/:id/endperiod' => 'userlogs#endperiod', :as => :endperiod_userlog

  root :to => 'page#main'

end

app/models/userlog.rb
class Userlog < ActiveRecord::Base
  attr_accessible :cfu_id, :operator_id, :schedule_id, :sim_id, :sumlimit_id, :user_id, :userperiod_id
  belongs_to :user
  belongs_to :sumlimit
  belongs_to :cfu
  belongs_to :schedule
  belongs_to :userperiod
  belongs_to :operator

  validates :user,:sumlimit,:cfu,:schedule,:sim_id,:operator , :presence => true

end

app/controllers/userlogs_controller.rb
class UserlogsController < ApplicationController
  # GET /userlogs
  # GET /userlogs.json
  def index
    @userlogs = Userlog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @userlogs }
    end
  end

  # GET /userlogs/1
  # GET /userlogs/1.json
  def show
    @userlog = Userlog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @userlog }
    end
  end

  # GET /userlogs/new
  # GET /userlogs/new.json
  def new
    #@userlog = Userlog.new
    @userperiod = Userperiod.new
    @userperiod.userlog.build
    @userperiod.datein = Time.zone.now
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @userlog }
    end
  end

  # GET /userlogs/1/edit
  def edit
    @userlog = Userlog.find(params[:id])
  end

  # POST /userlogs
  # POST /userlogs.json
  def create
    logger.debug params
    @userperiod = Userperiod.new(params[:userperiod])
    
    #@userlog = Userlog.new(params[:userlog])
    respond_to do |format|
      if @userperiod.save
        format.html { redirect_to Userlog, :notice => 'Userlog was successfully created.' }
        format.json { render :json => @userlog, :status => :created, :location => @userlog }
      else
        format.html { render :action => "new" }
        format.json { render :json => @userlog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /userlogs/1
  # PUT /userlogs/1.json
  def update
    @userlog = Userlog.find(params[:id])

    respond_to do |format|
      if @userlog.update_attributes(params[:userlog])
        format.html { redirect_to @userlog, :notice => 'Userlog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @userlog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /userlogs/1
  # DELETE /userlogs/1.json
  def destroy
    @userlog = Userlog.find(params[:id])
    @userlog.destroy

    respond_to do |format|
      format.html { redirect_to userlogs_url }
      format.json { head :no_content }
    end
  end

  def endperiod
    @userlog=Userlog.find(params[:id])
    @userlog.userperiod.endperiod
    #logger.debug "Привет #{@userlog.userperiod.endperiod}"
    @userlog.userperiod.save
    respond_to do |format|
      format.html { redirect_to userlogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/userlogs_helper.rb
module UserlogsHelper
end

app/views/userlogs/_form.html.erb
<%= form_for(@userlog) do |f| %>
  <% if @userlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userlog.errors.count, "error") %> prohibited this userlog from being saved:</h2>

      <ul>
      <% @userlog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :cfu_id %><br />
    <%= f.collection_select(:cfu_id, Cfu.all, :id, :namecfu) %>
  </div>
  <div class="field">
    <%= f.label :sumlimit_id %><br />
    <%= f.collection_select(:sumlimit_id, Sumlimit.all, :id, :namelimit) %>
  </div>
  <div class="field">
    <%= f.label :schedule_id %><br />
    <%= f.collection_select(:schedule_id, Schedule.all, :id, :timein ) %>
  </div>
  <div class="field">
    <%= f.label :userperiod_id %><br />
    <%= f.number_field :userperiod_id %>
  </div>
  <div class="field">
    <%= f.label :sim_id %><br />
    <%= f.number_field :sim_id %>
  </div>
  <div class="field">
    <%= f.label :operator_id %><br />
    <%= f.collection_select(:operator_id, Operator.all, :id, :opername) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/userlogs/_new_form.html.erb
<%= form_for @userperiod, :url => '/userlogs/', userlogs_path => false do |cf| %>
  <%= cf.fields_for :userlog do |f| %>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select(:user_id, User.all, :id, :secondname ) %>
  </div>
  <div class="field">
    <%= f.label :cfu_id %><br />
    <%= f.collection_select(:cfu_id, Cfu.all, :id, :namecfu) %>
  </div>
  <div class="field">
    <%= f.label :sumlimit_id %><br />
    <%= f.collection_select(:sumlimit_id, Sumlimit.all, :id, :namelimit) %>
  </div>
  <div class="field">
    <%= f.label :schedule_id %><br />
    <%= f.collection_select(:schedule_id, Schedule.all, :id, :timein ) %>
  </div>
  <div class="field">
    <%= f.label :sim_id %><br />
    <%= f.collection_select(:sim_id, Sim.where(:id =>Sim.notusesim_id), :id, :sirealnumber ) %>
  </div>
  <div class="field">
    <%= f.label :operator_id %><br />
    <%= f.collection_select(:operator_id, Operator.all, :id, :opername) %>
  </div>
  <% end %>
  <div class="field">
    <%= cf.label :datein_text %><br />
    <%= cf.text_field :datein_text %>
  </div>
  <div class="actions">
    <%= cf.submit %>
  </div>
<% end %>

app/views/userlogs/edit.html.erb
<h1>Editing userlog</h1>

<%= render 'form' %>

<%= link_to 'Show', @userlog %> |
<%= link_to 'Back', userlogs_path %>

app/views/userlogs/index.html.erb
<h1>Listing userlogs</h1>

<table>
  <tr>
    <th>User</th>
    <th>Cfu</th>
    <th>Sumlimit</th>
    <th>Schedule</th>
    <th>Userperiod</th>
    <th>Userperiod</th>
    <th>Sim</th>
    <th>Operator</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @userlogs.each do |userlog| %>
  <tr>
    <td><%= userlog.user.secondname %></td>
    <td><%= userlog.cfu.namecfu %></td>
    <td><%= userlog.sumlimit.namelimit %></td>
    <td><%= userlog.schedule.timein %> <%= userlog.schedule.timeout %></td>
    <td><%= userlog.userperiod.datein %></td>
    <td><%= userlog.userperiod.dateout %></td>
    <td><%= userlog.sim_id %></td>
    <td><%= userlog.operator.opername %></td>
    <td><%= link_to 'Show', userlog %></td>
    <td><%= link_to 'Edit', edit_userlog_path(userlog) %></td>
    <td><%= link_to 'Destroy', userlog, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
    <td><%= link_to 'Endperiod', endperiod_userlog_path(userlog), :data => { :confirm => 'Вы действительно хотите закрыть связь?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Userlog', new_userlog_path %>

app/views/userlogs/new.html.erb
<h1>New userlog</h1>

<%= render 'new_form' %>

<%= link_to 'Back', userlogs_path %>

app/views/userlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @userlog.user_id %>
</p>

<p>
  <b>Cfu:</b>
  <%= @userlog.cfu_id %>
</p>

<p>
  <b>Sumlimit:</b>
  <%= @userlog.sumlimit_id %>
</p>

<p>
  <b>Schedule:</b>
  <%= @userlog.schedule_id %>
</p>

<p>
  <b>Userperiod:</b>
  <%= @userlog.userperiod_id %>
</p>

<p>
  <b>Sim:</b>
  <%= @userlog.sim_id %>
</p>

<p>
  <b>Operator:</b>
  <%= @userlog.operator_id %>
</p>


<%= link_to 'Edit', edit_userlog_path(@userlog) %> |
<%= link_to 'Back', userlogs_path %>