config/routes.rb
Phone::Application.routes.draw do

  resources :simlogs

  resources :hollydays

  get "descriptioncalls/show"

  get "descriptioncalls/update"
  resources :userlogs
  resources :operators
  resources :schedules
  resources :cfus
  resources :sumlimits
  resources :users
  resources :simnumlogs
  resources :sims
  get "page/main"

  get "page/help"

  get "page/about"

  resources :tnumbers

  resources :tarifs
  resources :descriptioncalls
  resources :report
  match '/calllogs/' => 'calllogs#index', :via => :get
  match '/upload/' => 'upload#index', :via => :get
  match '/upload/' => 'upload#upload', :via => :post
  match '/simnumlogs/:id/endperiod' => 'simnumlogs#endperiod', :as => :endperiod_simnumlog
  match '/userlogs/:id/endperiod' => 'userlogs#endperiod', :as => :endperiod_userlog

  root :to => 'page#main'

end

app/models/simnumlog.rb
class Simnumlog < ActiveRecord::Base
  attr_accessible :sim_id, :simperiod_id, :tnumber_id
  belongs_to :sim
  belongs_to :simperiod
  belongs_to :tnumber
end

app/controllers/simnumlogs_controller.rb
class SimnumlogsController < ApplicationController
  # GET /simnumlogs
  # GET /simnumlogs.json
  def index
    @simnumlogs = Simnumlog.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @simnumlogs }
    end
  end

  # GET /simnumlogs/1
  # GET /simnumlogs/1.json
  def show
    @simnumlog = Simnumlog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @simnumlog }
    end
  end

  # GET /simnumlogs/new
  # GET /simnumlogs/new.json
  def new
    @simnumlog = Simnumlog.new
    #@simperiod = Simperiod.new
    #@tnumber
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @simnumlog }
    end
  end

  # GET /simnumlogs/1/edit
  def edit
    @simnumlog = Simnumlog.find(params[:id])
  end

  # POST /simnumlogs
  # POST /simnumlogs.json
  def create
    @simnumlog = Simnumlog.new(:sim_id => params[:simnumlog][:sim_id],:tnumber_id => params[:simnumlog][:tnumber_id])
    date = params[:simnumlog]["simperiod_id(1i)"] + '-'
    date = date + params[:simnumlog]["simperiod_id(2i)"].to_s + '-'
    date = date + params[:simnumlog]["simperiod_id(3i)"].to_s + ' '
    date = date + params[:simnumlog]["simperiod_id(4i)"].to_s + ':'
    date = date + params[:simnumlog]["simperiod_id(5i)"].to_s
    @simperiod = Simperiod.create(:datein => date) 
    @simnumlog.simperiod_id = @simperiod.id
    respond_to do |format|
    if @simnumlog.save
        format.html { redirect_to @simnumlog, :notice => date}
        format.json { render :json => @simnumlog, :status => :created, :location => @simnumlog }
      else
        format.html { render :action => "new" }
        format.json { render :json => @simnumlog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /simnumlogs/1
  # PUT /simnumlogs/1.json
  def update
    @simnumlog = Simnumlog.find(params[:id])

    respond_to do |format|
      if @simnumlog.update_attributes(params[:simnumlog])
        format.html { redirect_to @simnumlog, :notice => 'Simnumlog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @simnumlog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /simnumlogs/1
  # DELETE /simnumlogs/1.json
  def destroy
    @simnumlog = Simnumlog.find(params[:id])
    @simnumlog.destroy

    respond_to do |format|
      format.html { redirect_to simnumlogs_url }
      format.json { head :no_content }
    end
  end
  def endperiod
    @simnumlog = Simnumlog.find(params[:id])
    @simnumlog.simperiod.dateout=Time.now
    @simnumlog.simperiod.save
    respond_to do |format|
      format.html { redirect_to simnumlogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/simnumlogs_helper.rb
module SimnumlogsHelper
end

app/views/simnumlogs/_form.html.erb
<%= form_for(@simnumlog) do |f| %>
  <% if @simnumlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@simnumlog.errors.count, "error") %> prohibited this simnumlog from being saved:</h2>

      <ul>
      <% @simnumlog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tnumber_id %><br />
    <%= f.collection_select(:tnumber_id,  Tnumber.where(:id =>Tnumber.freetnumbers_id), :id, :voicenumber) %>
  </div>

  <div class="field">
    <%= f.label :sim_id %><br />
    <%= f.collection_select(:sim_id,  Sim.where(:id =>Sim.freesims_id), :id, :sirealnumber) %>
  </div>

  <div class="field">
    <%= f.label :simperiod_id %><br />
    <%= f.number_field :simperiod_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/simnumlogs/_new_form.html.erb
<%= form_for(@simnumlog) do |f| %>
  <% if @simnumlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@simnumlog.errors.count, "error") %> prohibited this simnumlog from being saved:</h2>

      <ul>
      <% @simnumlog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tnumber_id %><br />
    <%= f.collection_select(:tnumber_id,  Tnumber.where(:id =>Tnumber.freetnumbers_id), :id, :voicenumber) %>
  </div>

  <div class="field">
    <%= f.label :sim_id %><br />
    <%= f.collection_select(:sim_id,  Sim.where(:id =>Sim.freesims_id), :id, :sirealnumber) %>
  </div>

  <div class="field">
    <%= f.label :simperiod_id %><br />
    <%= f.datetime_select :simperiod_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/simnumlogs/edit.html.erb
<h1>Editing simnumlog</h1>

<%= render 'form' %>

<%= link_to 'Show', @simnumlog %> |
<%= link_to 'Back', simnumlogs_path %>

app/views/simnumlogs/index.html.erb
<h1>Listing simnumlogs</h1>

<table>
  <tr>
    <th>Tnumber</th>
    <th>Sim</th>
    <th>Simperiod</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @simnumlogs.each do |simnumlog| %>
  <tr>
    <td><%= simnumlog.tnumber.voicenumber %></td>
    <td><%= simnumlog.sim.sirealnumber %></td>
    <td><%= simnumlog.simperiod_id %></td>
    <td><%= simnumlog.simperiod.datein %></td>
    <td><%= simnumlog.simperiod.dateout %></td>
    <td><%= link_to 'Show', simnumlog %></td>
    <td><%= link_to 'Edit', edit_simnumlog_path(simnumlog) %></td>
    <td><%= link_to 'Destroy', simnumlog, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
    <td><%= link_to 'Endperiod', endperiod_simnumlog_path(simnumlog), :data => { :confirm => 'Вы действительно хотите закрыть связь?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Simnumlog', new_simnumlog_path %>

app/views/simnumlogs/new.html.erb
<h1>New simnumlog</h1>

<%= render 'new_form' %>

<%= link_to 'Back', simnumlogs_path %>

app/views/simnumlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tnumber:</b>
  <%= @simnumlog.tnumber_id %>
</p>

<p>
  <b>Sim:</b>
  <%= @simnumlog.sim_id %>
</p>

<p>
  <b>Simperiod:</b>
  <%= @simnumlog.simperiod_id %>
</p>


<%= link_to 'Edit', edit_simnumlog_path(@simnumlog) %> |
<%= link_to 'Back', simnumlogs_path %>